version: "3.4"
services:
  beego:
    container_name: beego
    image: muke5hy/go-api:beego-1.0.0
    build:
      context: ./go-api-api/beego
    ports:
      - 8080:80
    networks:
      - go-api
  echo:
    container_name: echo
    image: muke5hy/go-api:echo-1.0.0
    build:
      context: ./go-api-api/echo
    environment:
      - "ENVIRONMENT=DEBUG"
      - "REDIS_HOST=redis-db"
      - "REDIS_PORT=6379"
      - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
      - 81:10010
    networks:
      - go-api
  gin:
    container_name: gin
    image: muke5hy/go-api:gin-1.0.0
    build:
      context: ./go-api-api/gin
    environment:
      - "ENVIRONMENT=DEBUG"
      - "REDIS_HOST=redis-db"
      - "REDIS_PORT=6379"
      - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
      - 81:10010
    networks:
      - go-api
  plain:
    container_name: plain
    image: muke5hy/go-api:plain-1.0.0
    build:
      context: ./go-api-api/plain
    environment:
      - "ENVIRONMENT=DEBUG"
      - "REDIS_HOST=redis-db"
      - "REDIS_PORT=6379"
      - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
      - 81:10010
    networks:
      - go-api
  ui:
    container_name: ui
    image: muke5hy/go-api:ui-1.0.0
    build:
      context: ./ui
    environment:
      - "ENVIRONMENT=DEBUG"
      - "REDIS_HOST=redis-db"
      - "REDIS_PORT=6379"
      - "JAEGER_HOST_PORT=jaeger:6831"
    ports:
      - 81:10010
    networks:
      - go-api
  redis-db:
    container_name: redis-db
    image: redis:6.0-alpine
    command: ["redis-server", "--dir", "/tmp", "--appendonly", "yes"]
    volumes:
      - ./go-api-api/redis-db/appendonly.aof:/tmp/appendonly.aof
    networks:
      - go-api
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:latest
    networks:
      - go-api
    ports:
      - 16686:16686
      - 14269:14269
networks:
  go-api:
    name: go-api
